 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: blip2_vicuna_instruct_textinv
  load_finetuned: True
  load_pretrained: True

  pretrained: "https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/InstructBLIP/instruct_blip_vicuna7b_trimmed.pth"
  finetuned: "/home/infres/ziyliu-24/FakeParts2/Detectors/AntifakePrompt/ckpt/COCO_150k_SD3_SD2IP.pth" # SD2+IP (90k, postfix)
  # finetuned: "/home/infres/ziyliu-24/FakeParts2/Detectors/AntifakePrompt/ckpt/COCO_150k_SD3_SD2IP_lama.pth" # SD2+IP+LaMa (90k, postfix)
  
  # vit encoder
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: "fp16"
  freeze_vit: True

  # Q-Former
  num_query_token: 32

  # path to Vicuna checkpoint
  llm_model: "lmsys/vicuna-7b-v1.5"

  # generation configs
  prompt: "Is this photo real [*]?"
  # prompt: "[*] Is this photo real?"
  # prompt: "Is this photo [*]?"
  pseudo_word: "[*]"
  # init_word: "real"


preprocess:
    vis_processor:
        train:
          name: "blip2_image_train_textinv"
          image_size: 224
          # COCO+SD2+SD2IP (90K)
          mean: [0.4730, 0.4499, 0.4129]
          std: [0.2780, 0.2713, 0.2872]
          # # COCO+SD2+SD2IP+LaMa (90K)
          # mean: [0.4722, 0.4490, 0.4117]
          # std: [0.2772, 0.2708, 0.2867]
        eval:
          name: "blip_image_eval_textinv"
          image_size: 224
          # COCO+SD2+SD2IP (90K)
          mean: [0.4730, 0.4499, 0.4129]
          std: [0.2780, 0.2713, 0.2872]
          # # COCO+SD2+SD2IP+LaMa (90K)
          # mean: [0.4722, 0.4490, 0.4117]
          # std: [0.2772, 0.2708, 0.2867]
    text_processor:
        train:
          name: "blip_question_textinv"
          prompt: "Is this photo real [*]?"
          # prompt: "[*] Is this photo real?"
          # prompt: "Is this photo [*]?"
          pseudo_word: "[*]"
        eval:
          name: "blip_question_textinv"
          prompt: "Is this photo real [*]?"
          # prompt: "[*] Is this photo real?"
          # prompt: "Is this photo [*]?"
          pseudo_word: "[*]"
